name: CI
on:
  push: # run on every push to any branch
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Setup uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: pyproject.toml

      - name: Install package and test dependencies
        run: uv sync --extra dev

      # We only want to install this on one run, because otherwise we'll have
      # duplicate annotations.
      - name: Install error reporter
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        run: uv pip install pytest-github-actions-annotate-failures

      - name: Run Tests
        run: uv run pytest
