name: Publish to PyPI
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    if: github.repository == 'ml31415/numpy-groupies'
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: "3.12"
      - name: Build tarball and wheels
        run: |
          git clean -xdf
          git restore -SW .
          uv build
      - name: List contents of built dist
        run: |
          ls -ltrh
          ls -ltrh dist
      - name: Check built artifacts
        run: |
          uvx twine check --strict dist/*
          pwd
          if [ -f dist/numpy_groupies-0.0.0.tar.gz ]; then
            echo "❌ INVALID VERSION NUMBER"
            exit 1
          else
            echo "✅ Looks good"
          fi
      - name: Test artifact installation
        run: |
          uv venv --clear
          uv pip install dist/*.tar.gz
          uv run --no-sync python -c "import numpy_groupies; print(numpy_groupies.__version__)"
      - uses: actions/upload-artifact@v7
        with:
          name: release
          path: dist

  test-built-dist:
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: release
          path: dist
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TESTPYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  upload-to-pypi:
    needs: test-built-dist
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: release
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          skip-existing: true
